Repository GDSC-KJSIEIT/hacktober-fest, pull requests merged in 2022-10, with the labels that each got.

#4 Taaha's PR
  Competetive Programming/cp-contributor.md
Labels: documentation, hacktober, hacktoberfest-accepted

#5 Taaha
  Competitive Programming/Q1_Factorial/info.md
  Competitive Programming/Q2_ZeroMatrix/info.md
  Competitive Programming/Q3_MergeSortedArrays/info.md
  Competitive Programming/Q4_ReverseWordsStrings/info.md
  Competitive Programming/Q5_TwoSum/info.md
  Competitive Programming/Q6_NonRepeatLongestSubstring/info.md
  Competitive Programming/cp-contributor.md
  Competitive Programming/cp-contributors.md
  README.md
Labels: hacktober, hacktoberfest-accepted

#14 Set Matrix Zeroes
  Competitive Programming/Q2_ZeroMatrix/set_matrix.java
Labels: hacktober, hacktoberfest-accepted

#31 Added solution for Question7
  .gitignore
  Competitive Programming/Q7_LargestSubArr/ppq7.cpp
  Competitive Programming/cp-contributors.md
Labels: hacktober, hacktoberfest-accepted

#38 CP ques 1
  Competitive Programming/Q1_Factorial/ATN_factorial.cpp
  Competitive Programming/cp-contributors.md
Labels: hacktober, hacktoberfest-accepted

#34 Static Blog Website
  Web-Development/Blog Website/Readme.md
  Web-Development/Blog Website/index.html
  Web-Development/Blog Website/style.css
  Web-Development/web-d-contributor.md
Labels: hacktober, hacktoberfest-accepted

#37 solved cp q1 factorial
  Competitive Programming/Q1_Factorial/tdFactorial.c
  Competitive Programming/Q4_ReverseWordsStrings/TdRev.java
  Competitive Programming/cp-contributors.md
Labels: hacktober, hacktoberfest-accepted

#56 Add lottery contract
  Blockchain/Lottery.sol
Labels: hacktoberfest-accepted

#55 Solved CP Q1, Q2, Q3, Q4 and Q5
  Competitive Programming/Q1_Factorial/d-factorial.py
  Competitive Programming/Q2_ZeroMatrix/d-matrix.py
  Competitive Programming/Q3_MergeSortedArrays/d-sorted.py
  Competitive Programming/Q4_ReverseWordsStrings/d-reverse.py
  Competitive Programming/Q5_TwoSum/d-two-sum.py
  Competitive Programming/cp-contributors.md
Labels: hacktoberfest-accepted

#42 solved web dev Q1
  Web-Development/TD News website/css/styles.css
  Web-Development/TD News website/index.html
  Web-Development/TD News website/js/script.js
  Web-Development/web-d-contributor.md
Labels: hacktoberfest-accepted

#52 A pull request from my side
  Competitive Programming/Q1_Factorial/info.md
  Competitive Programming/Q1_Factorial/tanisha-factorial.py
  Competitive Programming/Q2_ZeroMatrix/Tanisha_matrix.c
  Competitive Programming/Q2_ZeroMatrix/info.md
  Competitive Programming/Q3_MergeSortedArrays/Tanisha-arrays.py
  Competitive Programming/Q3_MergeSortedArrays/info.md
  Competitive Programming/Q4_ReverseWordsStrings/Tanisha_reverse.py
  Competitive Programming/Q4_ReverseWordsStrings/info.md
  Competitive Programming/Q5_TwoSum/Tanisha_sum.py
  Competitive Programming/Q5_TwoSum/info.md
  Competitive Programming/Q6_NonRepeatLongestSubstring/Tanisha_sub.py
  Competitive Programming/Q6_NonRepeatLongestSubstring/info.md
  Competitive Programming/Q7_LargestSubArr/Tanisha_array.py
  Competitive Programming/Q7_LargestSubArr/info.md
  Competitive Programming/cp-contributors.md
  UI or UX/ui-ux-contributors.md
Labels: hacktober, hacktoberfest-accepted

#53 Solved TwoSum
  Competitive Programming/Q5_TwoSum/twoSum.cpp
Labels: hacktober, hacktoberfest-accepted

#32 Reversing strings program
  Competitive Programming/Q4_ReverseWordsStrings/sak_rev_string.py
  Web-Development/sak@newz/favicon.png
  Web-Development/sak@newz/index.php
  Web-Development/sak@newz/readme.md
  Web-Development/web-d-contributor.md
Labels: hacktober, hacktoberfest-accepted

#57 Finished Q1, Q2, Q7 (CP) and Q1 (UI/UX)
  .vscode/settings.json
  Competitive Programming/Q1_Factorial/YWFactorial.c
  Competitive Programming/Q2_ZeroMatrix/YWZeroMatrix.c
  Competitive Programming/Q7_LargestSubArr/YWLargestSubArr.c
  Competitive Programming/cp-contributors.md
  UI or UX/YW Fintech Company Logo.png
  UI or UX/ui-ux-contributors.md
Labels: hacktober, hacktoberfest-accepted

#58 solved cp q6 to find largest non repeating substring
  Competitive Programming/Q6_NonRepeatLongestSubstring/Tdq6.java
  Competitive Programming/cp-contributors.md
  UI or UX/Tdlogo/logo.png
  UI or UX/ui-ux-contributors.md
Labels: hacktober, hacktoberfest-accepted

#63 Added Shuffle Logo
  UI or UX/Shuffle.png
  UI or UX/ui-ux-contributors.md
Labels: hacktober, hacktoberfest-accepted

#39 Added GUI application in Python
  App-Development/IPV4_DecimalIP.py
  App-Development/app-contributor.md
Labels: hacktober, hacktoberfest-accepted

#65 Added Ecommerce Smart Contract
  Blockchain/Contracts-Krishi Chawda/Ecommerce.sol
  Blockchain/blockchain-contributor.md
Labels: hacktober, hacktoberfest-accepted

#71 Factorial of a number recursively
  Competitive Programming/Q1_Factorial/Mayank_factorial.java
  Competitive Programming/cp-contributors.md
Labels: hacktober, hacktoberfest-accepted

#76 Added NFT Contract
  Blockchain/Contracts-Krishi Chawda/Nft_contract.sol
Labels: hacktober, hacktoberfest-accepted

#82 Added ERC20 Contract and updated contributor.md
  Blockchain/Contracts-Krishi Chawda/Erc.sol
  Blockchain/blockchain-contributor.md
Labels: hacktober, hacktoberfest-accepted

#83 CP Q1 Solved
  Competitive Programming/cp-contributors.md
  Competitive Programming/fact-pruth.java
Labels: hacktober, hacktoberfest-accepted

#80 solved zeroMatrix -Q2 (CP)
  Competitive Programming/Q2_ZeroMatrix/sam_zeroMatrix.py
  Competitive Programming/cp-contributors.md
Labels: hacktober, hacktoberfest-accepted

#86 solved Q4(CP) - word reversal
  Competitive Programming/Q4_ReverseWordsStrings/sam_reverse_words.py
  Competitive Programming/cp-contributors.md
Labels: hacktoberfest-accepted

#73 Solved CP 1, 2, 3, 4 & added to cp-contributors.md
  Competitive Programming/Q1_Factorial/FactorialSD.java
  Competitive Programming/Q2_ZeroMatrix/ZeroMatrixSD.java
  Competitive Programming/Q3_MergeSortedArrays/MergeSortedArraysSD.java
  Competitive Programming/Q4_ReverseWordsStrings/ReverseWordsStringsSD.java
  Competitive Programming/cp-contributors.md
Labels: hacktoberfest-accepted

#84 Solved Q4 CP
  Competitive Programming/Q4_ReverseWordsStrings/YWReverseString.py
  Competitive Programming/Q6_NonRepeatLongestSubstring/YWNonRepeat.py
  Competitive Programming/cp-contributors.md
Labels: hacktoberfest-accepted

#72 Reverse Word Strings(Java)
  Competitive Programming/Q4_ReverseWordsStrings/mayank_reverse_word.java
  Competitive Programming/cp-contributors.md
Labels: hacktoberfest-accepted

#90 Portfolio website PP
  Web-Development/pruthvirajp04.github.io/README.md
  Web-Development/pruthvirajp04.github.io/about.html
  Web-Development/pruthvirajp04.github.io/contact.html
  Web-Development/pruthvirajp04.github.io/footer.html
  Web-Development/pruthvirajp04.github.io/index.html
  Web-Development/pruthvirajp04.github.io/js/menu.js
  Web-Development/pruthvirajp04.github.io/js/reuse.js
  Web-Development/pruthvirajp04.github.io/js/theme.js
  Web-Development/pruthvirajp04.github.io/js/type.js
  Web-Development/pruthvirajp04.github.io/navbar.html
  Web-Development/pruthvirajp04.github.io/skills.html
  Web-Development/pruthvirajp04.github.io/static/css/aboutstyle.css
  Web-Development/pruthvirajp04.github.io/static/css/contactstyle.css
  Web-Development/pruthvirajp04.github.io/static/css/footer.css
  Web-Development/pruthvirajp04.github.io/static/css/navbar.css
  Web-Development/pruthvirajp04.github.io/static/css/responsive.css
  Web-Development/pruthvirajp04.github.io/static/css/scroller.css
  Web-Development/pruthvirajp04.github.io/static/css/skills-responsive.css
  Web-Development/pruthvirajp04.github.io/static/css/skillsstyle.css
  Web-Development/pruthvirajp04.github.io/static/css/style.css
  Web-Development/pruthvirajp04.github.io/static/css/theme.css
  Web-Development/pruthvirajp04.github.io/static/img/chess.com.png
  Web-Development/pruthvirajp04.github.io/static/img/cpp-logo.png
  Web-Development/pruthvirajp04.github.io/static/img/csilogo.jpg
  Web-Development/pruthvirajp04.github.io/static/img/css-logo.png
  Web-Development/pruthvirajp04.github.io/static/img/favicon.JPG
  Web-Development/pruthvirajp04.github.io/static/img/github.png
  Web-Development/pruthvirajp04.github.io/static/img/gmail.png
  Web-Development/pruthvirajp04.github.io/static/img/html-logo.png
  Web-Development/pruthvirajp04.github.io/static/img/instagram.png
  Web-Development/pruthvirajp04.github.io/static/img/js-logo.png
  Web-Development/pruthvirajp04.github.io/static/img/lichess.jpg
  Web-Development/pruthvirajp04.github.io/static/img/linkedin.png
  Web-Development/pruthvirajp04.github.io/static/img/mongodb-logo.jpg
  Web-Development/pruthvirajp04.github.io/static/img/myphoto.jpg
  Web-Development/pruthvirajp04.github.io/static/img/nodejs-logo.png
  Web-Development/pruthvirajp04.github.io/static/img/react-logo.png
  Web-Development/pruthvirajp04.github.io/theme.html
  Web-Development/web-d-contributor.md
Labels: hacktober, hacktoberfest-accepted

#93 Solved Q1 from CP domain
  Competitive Programming/Q1_Factorial/SS_Factorial.c
  Competitive Programming/Q4_ReverseWordsStrings/SS_reverse.py
  Competitive Programming/Q5_TwoSum/SS_sum.c
  Competitive Programming/Q6_NonRepeatLongestSubstring/SS_long.py
  Competitive Programming/cp-contributors.md
Labels: hacktoberfest-accepted

#89 CP 5, 6, 7
  Competitive Programming/Q5_TwoSum/TwoSumSD.java
  Competitive Programming/Q6_NonRepeatLongestSubstring/NonRepeatLongestSubstringSD.java
  Competitive Programming/Q7_LargestSubArr/LargestSubArrSD.java
  Competitive Programming/cp-contributors.md
Labels: hacktoberfest-accepted

#97 cp6
  Competitive Programming/Q2_ZeroMatrix/cp2.py
  Competitive Programming/Q5_TwoSum/cp5.py
  Competitive Programming/Q6_NonRepeatLongestSubstring/cp6.py
  Competitive Programming/cp-contributors.md
Labels: hacktober, hacktoberfest-accepted
